language: objective-c
xcode_project: Tests/Tests.xcodeproj
matrix:
  include:
    - xcode_sdk: iphonesimulator
      xcode_scheme: Demo
before_install:
  - brew update
  - brew unlink xctool
  - brew install xctool
